apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduscan-gateway
  namespace: eduscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduscan-gateway
  template:
    metadata:
      labels:
        app: eduscan-gateway
    spec:
      containers:
      - name: gateway
        image: ingrij27/eduscan-gateway:latest
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduscan-ia
  namespace: eduscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduscan-ia
  template:
    metadata:
      labels:
        app: eduscan-ia
    spec:
      containers:
      - name: ia-modelo
        image: ingrij27/eduscan-ia_modelo:latest
        ports:
        - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduscan-procesamiento
  namespace: eduscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduscan-procesamiento
  template:
    metadata:
      labels:
        app: eduscan-procesamiento
    spec:
      containers:
      - name: procesamiento
        image: ingrij27/eduscan-procesamiento:latest
        ports:
        - containerPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduscan-database
  namespace: eduscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduscan-database
  template:
    metadata:
      labels:
        app: eduscan-database
    spec:
      containers:
      - name: database-api
        image: ingrij27/eduscan-database_api:latest
        ports:
        - containerPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: eduscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "eduscan"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_USER
          value: "postgres"